version: '3.7'

services:
  mongodb:
    image: mongo:4.2.5
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=test123
      - MONGO_INITDB_DATABASE=garrage
    volumes:
      - ./docker/garrage/init-scripts:/docker-entrypoint-initdb.d:ro

  mongo-express:
    image: mongo-express:0.54.0
    depends_on:
      - mongodb
    restart: always
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongodb
      - ME_CONFIG_MONGODB_PORT=27017
      - ME_CONFIG_MONGODB_ADMINUSERNAME=root
      - ME_CONFIG_MONGODB_ADMINPASSWORD=test123
